### PR TITLE
Fix SEGV in run_combination_test.py

### PR DESCRIPTION
**Pull request by gwtnb**
Fix SEGV in run_combination_test.py

### CODE REVIEW

**Comment by unnonouno** [comment]
What happens?

**Comment by gwtnb** [comment]
When running `nosetests` with h5py and numpy 1.9, it fails with SEGV.

```
01:51:18 + nosetests --processes=4 --process-timeout=10000 --stop --with-coverage --cover-branches --cover-package=chainer,cupy -a !slow
01:51:20 Segmentation fault
```

**Comment by unnonouno** [comment]
h5py depends on `numpy>=1.7`. Is this a bug of h5py?
https://github.com/h5py/h5py/blob/master/setup.py#L27

**Comment by gwtnb** [comment]
I am not sure.

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
