### PR TITLE
Install h5py and theano before numpy in run_multi_test.py

### PR DESCRIPTION
**Pull request by gwtnb**
Note that numpy is required to install h5py.

Ref: #194

### CODE REVIEW

**Comment by unnonouno** [comment]
Do we need to restrict numpy version more precisely? This fix cannot install newer version of numpy.

**Comment by gwtnb** [comment]
`pip install numpy<some version` is executed after installing h5py, so newer version of numpy may be installed.

**Comment by gwtnb** [comment]
`s/pip install/pip install -U/`

**Comment by unnonouno** [comment]
OK, i see.

**Pull request merged**
