### PR TITLE
Generate example coverage

### PR DESCRIPTION
**Pull request by unnonouno**
Generate `coverage.xml` file for jenkins.

### CODE REVIEW

**Comment by delta2323** [comment]
I am not certain that generating `coverage.xml` is enough to make Jenkins show the coverage. Could you give me some references (manual, document etc.) about measuring coverage in Jenkins?

**Comment by unnonouno** [comment]
We are now using cobertua plugin to show coverage graph in jenkins. It uses coverage.xml file. https://wiki.jenkins-ci.org/display/JENKINS/Cobertura+Plugin

**Comment by delta2323** [comment]
@unnonouno I got it. Thank you. LGTM :+1:

**Comment by delta2323** [comment]
Could you check the coverage report actually works?

**Pull request merged**
