### PR TITLE
Improve shuffle algorithm for cuda combination

### PR DESCRIPTION
**Pull request by toslunar**
This PR improves the shuffle heuristics (#537) by setting weights on each cuda lib.  The change fixes the following issue.

After #623, `daily_master_cupy-shuffled` will not have CUDA 9.2 configuration (for id in range(21)).  It may be because `cuda92` has a fewer number of `cuda_libs` combinations than other cuda versions.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
Failed 😔

Shuffle parameters:

`--id 2`
```
14:55:16 wheel: False
14:55:16 cython: 0.29.13
14:55:16 cuda_libs: ('cuda102', 'cudnn76-cuda102', 'none', 'cutensor1.2.0-cuda102')
14:55:16 base: ubuntu18_py36
14:55:16 pip: 8
14:55:16 numpy: 1.17
```

`--id 3`
```
14:58:29 wheel: False
14:58:29 cython: 0.29.14
14:58:29 cuda_libs: ('cuda111', 'cudnn80-cuda111', 'none', 'cutensor1.2.1-cuda111')
14:58:29 base: ubuntu16_py36-pyenv
14:58:29 pip: None
14:58:29 numpy: 1.16
```

`--id 4`
```
15:10:42 wheel: True
15:10:42 cython: 0.29.13
15:10:42 cuda_libs: ('cuda101', 'cudnn75-cuda101', 'nccl2.7-cuda101', 'none')
15:10:42 base: ubuntu18_py37-pyenv
15:10:42 pip: 9
15:10:42 numpy: 1.17
```

**Comment by toslunar** [comment]
Jenkins, test this please.

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
I can't reproduce this locally with 
`./run_cupy_install_test.py --id 2` even by forcing the conf to the one is in jenkins manually ...
Maybe some ccache state?

**Comment by emcastillo** [comment]
The error will be solved with https://github.com/cupy/cupy/pull/4619

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
The error seems to be a timeout. I wonder if re-running it several times will cache all the kernels

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Finally the tests passed :D

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
Let me close this issue as all tests are now migrated to the new infrastructure.
Thanks @toslunar and all those who worked on this repository.

**Pull request closed without merging**
